#include "PackageManager.hpp"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iomanip>
#include <sstream>
#include <string_view>
#include <unordered_map>
#include <unordered_set>

#include "NativePackage.hpp"
#include "PackageManifest.hpp"

namespace {

#if defined(__APPLE__)
constexpr const char* kPackageLibraryFileName = "package.dylib";
#else
constexpr const char* kPackageLibraryFileName = "package.so";
#endif

constexpr const char* kProjectManifestFileName = "mog.toml";
constexpr const char* kLockfileName = "mog.lock";
constexpr const char* kInstallRegistryFileName = "registry.toml";
constexpr const char* kPackageApiFileName = "package.api.mog";
constexpr const char* kLockfileHeader = "# Generated by mog install. Do not edit by hand.";
constexpr const char* kCacheMetadataFileName = ".metadata.toml";

std::string trim(std::string_view text) {
    size_t start = 0;
    while (start < text.size() &&
           std::isspace(static_cast<unsigned char>(text[start]))) {
        ++start;
    }

    size_t end = text.size();
    while (end > start &&
           std::isspace(static_cast<unsigned char>(text[end - 1]))) {
        --end;
    }

    return std::string(text.substr(start, end - start));
}

std::string stripComment(std::string_view line) {
    bool inString = false;
    for (size_t index = 0; index < line.size(); ++index) {
        if (line[index] == '"' && (index == 0 || line[index - 1] != '\\')) {
            inString = !inString;
            continue;
        }
        if (!inString && line[index] == '#') {
            return trim(line.substr(0, index));
        }
    }
    return trim(line);
}

bool parseQuotedString(const std::string& value, std::string& out,
                       std::string& outError) {
    if (value.size() < 2 || value.front() != '"' || value.back() != '"') {
        outError = "Expected quoted string value.";
        return false;
    }

    out.clear();
    for (size_t index = 1; index + 1 < value.size(); ++index) {
        char ch = value[index];
        if (ch == '\\' && index + 1 < value.size() - 1) {
            ++index;
            char escaped = value[index];
            switch (escaped) {
                case '\\':
                case '"':
                    out.push_back(escaped);
                    break;
                case 'n':
                    out.push_back('\n');
                    break;
                case 't':
                    out.push_back('\t');
                    break;
                default:
                    outError = "Unsupported escape sequence in string value.";
                    return false;
            }
            continue;
        }
        out.push_back(ch);
    }

    return true;
}

bool parseBoolValue(const std::string& value, bool& out, std::string& outError) {
    if (value == "true") {
        out = true;
        return true;
    }
    if (value == "false") {
        out = false;
        return true;
    }
    outError = "Expected boolean value.";
    return false;
}

bool parseQuotedStringArray(const std::string& value,
                            std::vector<std::string>& outValues,
                            std::string& outError) {
    outValues.clear();
    if (value.size() < 2 || value.front() != '[' || value.back() != ']') {
        outError = "Expected array value.";
        return false;
    }

    std::string body = trim(std::string_view(value).substr(1, value.size() - 2));
    while (!body.empty()) {
        size_t valueLength = 0;
        bool inString = false;
        bool escaped = false;
        for (; valueLength < body.size(); ++valueLength) {
            const char ch = body[valueLength];
            if (inString) {
                if (escaped) {
                    escaped = false;
                } else if (ch == '\\') {
                    escaped = true;
                } else if (ch == '"') {
                    inString = false;
                }
                continue;
            }

            if (ch == '"') {
                inString = true;
                continue;
            }
            if (ch == ',') {
                break;
            }
        }

        std::string parsed;
        if (!parseQuotedString(trim(body.substr(0, valueLength)), parsed, outError)) {
            return false;
        }
        outValues.push_back(parsed);

        if (valueLength >= body.size()) {
            body.clear();
        } else {
            body = trim(std::string_view(body).substr(valueLength + 1));
        }
    }

    return true;
}

std::string quoteTomlString(const std::string& text) {
    std::string out;
    out.reserve(text.size() + 2);
    out.push_back('"');
    for (char ch : text) {
        switch (ch) {
            case '\\':
            case '"':
                out.push_back('\\');
                out.push_back(ch);
                break;
            case '\n':
                out += "\\n";
                break;
            case '\t':
                out += "\\t";
                break;
            default:
                out.push_back(ch);
                break;
        }
    }
    out.push_back('"');
    return out;
}

std::string quoteTomlArray(const std::vector<std::string>& values) {
    std::ostringstream out;
    out << "[";
    for (size_t index = 0; index < values.size(); ++index) {
        if (index > 0) {
            out << ", ";
        }
        out << quoteTomlString(values[index]);
    }
    out << "]";
    return out.str();
}

std::string canonicalOrLexical(const std::filesystem::path& path) {
    std::error_code ec;
    const std::filesystem::path resolved =
        std::filesystem::weakly_canonical(path, ec);
    if (ec) {
        return path.lexically_normal().string();
    }
    return resolved.string();
}

bool fileExists(const std::filesystem::path& path) {
    std::error_code ec;
    return std::filesystem::exists(path, ec) && !ec;
}

bool isDirectory(const std::filesystem::path& path) {
    std::error_code ec;
    return std::filesystem::is_directory(path, ec) && !ec;
}

std::string defaultProjectName(const std::string& projectRoot) {
    const std::filesystem::path path(projectRoot);
    const std::string stem = path.filename().string();
    return stem.empty() ? "mog-project" : stem;
}

std::string normalizeRelativePath(std::string pathText) {
    std::replace(pathText.begin(), pathText.end(), '\\', '/');
    return pathText;
}

bool parseDependencyInlineTable(const std::string& value,
                                ProjectDependencySpec& outDependency,
                                std::string& outError) {
    if (value.size() < 2 || value.front() != '{' || value.back() != '}') {
        outError = "Dependency entries must be inline tables.";
        return false;
    }

    std::string body = trim(std::string_view(value).substr(1, value.size() - 2));
    while (!body.empty()) {
        const size_t equals = body.find('=');
        if (equals == std::string::npos) {
            outError = "Dependency table must use key = value entries.";
            return false;
        }

        const std::string key = trim(std::string_view(body).substr(0, equals));
        body = trim(std::string_view(body).substr(equals + 1));
        if (body.empty()) {
            outError = "Dependency table entry is missing a value.";
            return false;
        }

        size_t valueLength = 0;
        bool inString = false;
        bool escaped = false;
        for (; valueLength < body.size(); ++valueLength) {
            const char ch = body[valueLength];
            if (inString) {
                if (escaped) {
                    escaped = false;
                } else if (ch == '\\') {
                    escaped = true;
                } else if (ch == '"') {
                    inString = false;
                }
                continue;
            }

            if (ch == '"') {
                inString = true;
                continue;
            }

            if (ch == ',') {
                break;
            }
        }

        const std::string rawValue = trim(body.substr(0, valueLength));
        if (key == "path") {
            std::string parsed;
            if (!parseQuotedString(rawValue, parsed, outError)) {
                return false;
            }
            outDependency.path = normalizeRelativePath(parsed);
        } else if (key == "package") {
            std::string parsed;
            if (!parseQuotedString(rawValue, parsed, outError)) {
                return false;
            }
            outDependency.packageId = parsed;
        } else if (key == "version") {
            std::string parsed;
            if (!parseQuotedString(rawValue, parsed, outError)) {
                return false;
            }
            outDependency.version = parsed;
        } else if (key == "git") {
            std::string parsed;
            if (!parseQuotedString(rawValue, parsed, outError)) {
                return false;
            }
            outDependency.git = parsed;
        } else if (key == "registry") {
            std::string parsed;
            if (!parseQuotedString(rawValue, parsed, outError)) {
                return false;
            }
            outDependency.registry = parsed;
        } else if (key == "workspace") {
            if (!parseBoolValue(rawValue, outDependency.workspace, outError)) {
                return false;
            }
        } else {
            outError = "Unsupported dependency field '" + key + "'.";
            return false;
        }

        if (valueLength >= body.size()) {
            body.clear();
        } else {
            body = trim(std::string_view(body).substr(valueLength + 1));
        }
    }

    if (outDependency.path.empty() && !outDependency.workspace &&
        outDependency.git.empty() && outDependency.registry.empty() &&
        outDependency.packageId.empty()) {
        outError = "Dependency entries must define path, workspace, git, registry, or package metadata.";
        return false;
    }

    return true;
}

std::string readFileText(const std::filesystem::path& path) {
    std::ifstream file(path, std::ios::binary);
    if (!file) {
        return "";
    }
    return std::string((std::istreambuf_iterator<char>(file)),
                       std::istreambuf_iterator<char>());
}

std::string hashString(std::string_view text) {
    uint64_t hash = 1469598103934665603ull;
    for (unsigned char ch : text) {
        hash ^= static_cast<uint64_t>(ch);
        hash *= 1099511628211ull;
    }

    std::ostringstream out;
    out << std::hex << std::setfill('0') << std::setw(16) << hash;
    return out.str();
}

std::string digestFile(const std::filesystem::path& path) {
    return hashString(readFileText(path));
}

std::string manifestDigestForDir(const std::filesystem::path& packageDir) {
    const std::filesystem::path mogManifest = packageDir / kProjectManifestFileName;
    if (fileExists(mogManifest)) {
        return digestFile(mogManifest);
    }

    const std::filesystem::path legacyManifest = packageDir / "package.toml";
    if (fileExists(legacyManifest)) {
        return digestFile(legacyManifest);
    }

    return "";
}

std::vector<std::string> sortedUniqueStrings(std::vector<std::string> values) {
    std::sort(values.begin(), values.end());
    values.erase(std::unique(values.begin(), values.end()), values.end());
    return values;
}

bool removePathIfExists(const std::filesystem::path& path, std::string& outError) {
    std::error_code ec;
    if (!std::filesystem::exists(path, ec) && !std::filesystem::is_symlink(path, ec)) {
        return true;
    }
    std::filesystem::remove_all(path, ec);
    if (ec) {
        outError = "Could not remove '" + path.string() + "'.";
        return false;
    }
    return true;
}

bool ensureParentDirectory(const std::filesystem::path& path, std::string& outError) {
    std::error_code ec;
    std::filesystem::create_directories(path.parent_path(), ec);
    if (ec) {
        outError = "Could not create directory '" + path.parent_path().string() + "'.";
        return false;
    }
    return true;
}

bool copyFileReplacing(const std::filesystem::path& from,
                       const std::filesystem::path& to,
                       std::string& outError) {
    if (!ensureParentDirectory(to, outError)) {
        return false;
    }

    std::error_code ec;
    std::filesystem::copy_file(from, to,
                               std::filesystem::copy_options::overwrite_existing,
                               ec);
    if (ec) {
        outError = "Could not copy '" + from.string() + "' to '" + to.string() + "'.";
        return false;
    }
    return true;
}

bool copyDirectoryRecursive(const std::filesystem::path& from,
                            const std::filesystem::path& to,
                            std::string& outError) {
    std::error_code ec;
    std::filesystem::create_directories(to, ec);
    if (ec) {
        outError = "Could not create directory '" + to.string() + "'.";
        return false;
    }

    std::filesystem::recursive_directory_iterator it(from, ec), end;
    for (; !ec && it != end; it.increment(ec)) {
        const std::filesystem::path relative = it->path().lexically_relative(from);
        const std::filesystem::path destination = to / relative;
        if (it->is_directory(ec)) {
            std::filesystem::create_directories(destination, ec);
            if (ec) {
                outError = "Could not create directory '" + destination.string() + "'.";
                return false;
            }
            continue;
        }

        if (!it->is_regular_file(ec)) {
            continue;
        }

        if (!copyFileReplacing(it->path(), destination, outError)) {
            return false;
        }
    }

    if (ec) {
        outError = "Could not copy directory '" + from.string() + "'.";
        return false;
    }

    return true;
}

std::filesystem::path installRoot(const std::filesystem::path& projectRoot) {
    return projectRoot / ".mog" / "install";
}

std::filesystem::path installPackagesRoot(const std::filesystem::path& projectRoot) {
    return installRoot(projectRoot) / "packages";
}

std::filesystem::path installRegistryPath(const std::filesystem::path& projectRoot) {
    return installRoot(projectRoot) / kInstallRegistryFileName;
}

std::filesystem::path userCacheRoot() {
    if (const char* cacheDir = std::getenv("MOG_CACHE_DIR");
        cacheDir != nullptr && *cacheDir != '\0') {
        return std::filesystem::path(cacheDir) / "packages";
    }

    if (const char* xdgCache = std::getenv("XDG_CACHE_HOME");
        xdgCache != nullptr && *xdgCache != '\0') {
        return std::filesystem::path(xdgCache) / "mog" / "packages";
    }

    if (const char* home = std::getenv("HOME"); home != nullptr && *home != '\0') {
        return std::filesystem::path(home) / ".cache" / "mog" / "packages";
    }

    return std::filesystem::temp_directory_path() / "mog-cache" / "packages";
}

std::filesystem::path localCacheRoot() {
    return userCacheRoot() / "local";
}

std::filesystem::path projectFallbackCacheRoot(
    const std::filesystem::path& projectRoot) {
    return projectRoot / ".mog" / "cache" / "packages" / "local";
}

std::filesystem::path preferredLocalCacheRoot(
    const std::filesystem::path& projectRoot) {
    const std::filesystem::path preferred = localCacheRoot();
    std::error_code ec;
    std::filesystem::create_directories(preferred, ec);
    if (!ec) {
        return preferred;
    }
    return projectFallbackCacheRoot(projectRoot);
}

std::filesystem::path cacheMetadataPath(const std::filesystem::path& cacheDir) {
    return cacheDir / kCacheMetadataFileName;
}

std::string inferWorkspaceRoot(const std::filesystem::path& packageDir,
                               const PackageRegistryEntry& entry,
                               const std::string& fallbackProjectRoot) {
    std::filesystem::path current = packageDir;
    while (!current.empty()) {
        const std::filesystem::path candidateLibrary =
            current / "build" / "packages" / entry.packageNamespace /
            entry.packageName / kPackageLibraryFileName;
        if (fileExists(candidateLibrary)) {
            return current.string();
        }
        if (current == current.root_path()) {
            break;
        }
        current = current.parent_path();
    }

    return fallbackProjectRoot;
}

bool loadPackageEntryFromDir(const std::filesystem::path& packageDir,
                             PackageRegistryEntry& outEntry,
                             std::vector<std::string>* outDependencies,
                             std::string& outError) {
    PackageManifest manifest;
    if (!loadPackageManifest(packageDir.string(), manifest, outError)) {
        return false;
    }

    outEntry = PackageRegistryEntry{};
    outEntry.importName = manifest.importName.empty() ? manifest.packageName
                                                      : manifest.importName;
    outEntry.packageNamespace = manifest.packageNamespace;
    outEntry.packageName = manifest.packageName;
    outEntry.packageId = makePackageId(manifest.packageNamespace, manifest.packageName);
    outEntry.version = manifest.version;
    outEntry.packageDir = canonicalOrLexical(packageDir);
    outEntry.kind = manifest.kind.empty() ? "native" : manifest.kind;
    outEntry.description = manifest.description;
    outEntry.dependencyIds = manifest.dependencies;
    outEntry.sourceType = "path";
    outEntry.sourcePath = canonicalOrLexical(packageDir);
    outEntry.manifestDigest = manifestDigestForDir(packageDir);

    if (outEntry.kind == "source") {
        std::filesystem::path entryPath = manifest.entry.empty()
                                              ? packageDir / "src" / "main.mog"
                                              : packageDir / manifest.entry;
        outEntry.entryPath = canonicalOrLexical(entryPath);
    } else if (!manifest.library.empty()) {
        outEntry.libraryPath = canonicalOrLexical(packageDir / manifest.library);
    } else {
        const std::filesystem::path directLibrary =
            packageDir / kPackageLibraryFileName;
        if (fileExists(directLibrary)) {
            outEntry.libraryPath = canonicalOrLexical(directLibrary);
        }
    }

    const std::filesystem::path apiPath = packageDir / kPackageApiFileName;
    if (fileExists(apiPath)) {
        outEntry.apiPath = canonicalOrLexical(apiPath);
        outEntry.apiDigest = digestFile(apiPath);
    }

    if (outDependencies != nullptr) {
        *outDependencies = manifest.dependencies;
    }

    return true;
}

std::string normalizePackageIdLikeSpecifier(const std::string& rawSpecifier) {
    if (rawSpecifier.find(':') != std::string::npos) {
        return rawSpecifier;
    }

    const size_t slash = rawSpecifier.find('/');
    if (slash == std::string::npos) {
        return "";
    }

    return rawSpecifier.substr(0, slash) + ":" + rawSpecifier.substr(slash + 1);
}

bool relativePathString(const std::filesystem::path& from,
                        const std::filesystem::path& to,
                        std::string& outPath) {
    std::error_code ec;
    std::filesystem::path relative = std::filesystem::relative(to, from, ec);
    if (ec) {
        outPath = normalizeRelativePath(to.lexically_normal().string());
        return false;
    }
    outPath = normalizeRelativePath(relative.lexically_normal().string());
    return true;
}

bool writeInstallRegistryFile(const std::filesystem::path& outputPath,
                              const std::filesystem::path& projectRoot,
                              const std::vector<PackageRegistryEntry>& entries,
                              std::string& outError) {
    std::error_code ec;
    std::filesystem::create_directories(outputPath.parent_path(), ec);
    if (ec) {
        outError = "Could not create install directory '" +
                   outputPath.parent_path().string() + "'.";
        return false;
    }

    std::ofstream out(outputPath);
    if (!out) {
        outError = "Could not open '" + outputPath.string() + "' for writing.";
        return false;
    }

    out << kLockfileHeader << "\n";
    out << "schema_version = " << quoteTomlString("install.v1") << "\n";
    for (const auto& entry : entries) {
        out << "\n[[package]]\n";
        out << "name = " << quoteTomlString(entry.importName) << "\n";
        out << "package_id = " << quoteTomlString(entry.packageId) << "\n";
        out << "namespace = " << quoteTomlString(entry.packageNamespace) << "\n";
        out << "package_name = " << quoteTomlString(entry.packageName) << "\n";
        out << "version = " << quoteTomlString(entry.version) << "\n";
        out << "kind = " << quoteTomlString(entry.kind) << "\n";
        out << "dependency_groups = "
            << quoteTomlArray(sortedUniqueStrings(entry.dependencyGroups)) << "\n";

        std::string packageDirRelative;
        relativePathString(projectRoot, entry.packageDir, packageDirRelative);
        out << "package_dir = " << quoteTomlString(packageDirRelative) << "\n";
        if (!entry.sourceType.empty()) {
            out << "source_type = " << quoteTomlString(entry.sourceType) << "\n";
        }
        if (!entry.sourcePath.empty()) {
            std::string relativeSourcePath;
            relativePathString(projectRoot, entry.sourcePath, relativeSourcePath);
            out << "source_path = " << quoteTomlString(relativeSourcePath) << "\n";
        }
        if (!entry.manifestDigest.empty()) {
            out << "manifest_digest = " << quoteTomlString(entry.manifestDigest)
                << "\n";
        }
        if (!entry.apiDigest.empty()) {
            out << "api_digest = " << quoteTomlString(entry.apiDigest) << "\n";
        }

        if (!entry.entryPath.empty()) {
            std::string relative;
            relativePathString(projectRoot, entry.entryPath, relative);
            out << "entry = " << quoteTomlString(relative) << "\n";
        }
        if (!entry.libraryPath.empty()) {
            std::string relative;
            relativePathString(projectRoot, entry.libraryPath, relative);
            out << "library = " << quoteTomlString(relative) << "\n";
        }
        if (!entry.apiPath.empty()) {
            std::string relative;
            relativePathString(projectRoot, entry.apiPath, relative);
            out << "api = " << quoteTomlString(relative) << "\n";
        }
        if (!entry.description.empty()) {
            out << "description = " << quoteTomlString(entry.description) << "\n";
        }
    }

    return true;
}

bool writeLockfile(const std::filesystem::path& outputPath,
                   const std::filesystem::path& projectRoot,
                   const std::vector<PackageRegistryEntry>& entries,
                   std::string& outError) {
    std::ofstream out(outputPath);
    if (!out) {
        outError = "Could not open '" + outputPath.string() + "' for writing.";
        return false;
    }

    out << kLockfileHeader << "\n";
    out << "schema_version = " << quoteTomlString("lock.v1") << "\n";
    for (const auto& entry : entries) {
        out << "\n[[package]]\n";
        out << "name = " << quoteTomlString(entry.importName) << "\n";
        out << "package_id = " << quoteTomlString(entry.packageId) << "\n";
        out << "namespace = " << quoteTomlString(entry.packageNamespace) << "\n";
        out << "package_name = " << quoteTomlString(entry.packageName) << "\n";
        out << "version = " << quoteTomlString(entry.version) << "\n";
        out << "kind = " << quoteTomlString(entry.kind) << "\n";
        out << "dependency_groups = "
            << quoteTomlArray(sortedUniqueStrings(entry.dependencyGroups)) << "\n";
        out << "source_type = " << quoteTomlString(entry.sourceType) << "\n";
        std::string relativeSourcePath;
        relativePathString(projectRoot, entry.sourcePath, relativeSourcePath);
        out << "source_path = " << quoteTomlString(relativeSourcePath) << "\n";
        out << "dependencies = " << quoteTomlArray(entry.dependencyIds) << "\n";
        if (!entry.manifestDigest.empty()) {
            out << "manifest_digest = " << quoteTomlString(entry.manifestDigest)
                << "\n";
        }
        if (!entry.apiDigest.empty()) {
            out << "api_digest = " << quoteTomlString(entry.apiDigest) << "\n";
        }
    }

    return true;
}

struct PackageNode {
    PackageRegistryEntry entry;
    std::filesystem::path packageDir;
};

struct DependencyRoot {
    PackageNode node;
    std::string group;
};

struct CacheEntryMetadata {
    std::string packageId;
    std::string version;
    std::string kind;
    std::string sourceType;
    std::string sourcePath;
    std::string manifestDigest;
    std::string apiDigest;
    std::vector<std::string> dependencyGroups;
};

bool writeCacheMetadataFile(const std::filesystem::path& outputPath,
                            const PackageRegistryEntry& entry,
                            std::string& outError) {
    std::ofstream out(outputPath);
    if (!out) {
        outError =
            "Could not open cache metadata '" + outputPath.string() + "' for writing.";
        return false;
    }

    out << "package_id = " << quoteTomlString(entry.packageId) << "\n";
    out << "version = " << quoteTomlString(entry.version) << "\n";
    out << "kind = " << quoteTomlString(entry.kind) << "\n";
    out << "source_type = " << quoteTomlString(entry.sourceType) << "\n";
    out << "source_path = " << quoteTomlString(entry.sourcePath) << "\n";
    out << "manifest_digest = " << quoteTomlString(entry.manifestDigest) << "\n";
    out << "api_digest = " << quoteTomlString(entry.apiDigest) << "\n";
    out << "dependency_groups = "
        << quoteTomlArray(sortedUniqueStrings(entry.dependencyGroups)) << "\n";
    return true;
}

bool loadCacheMetadataFile(const std::filesystem::path& metadataPath,
                           CacheEntryMetadata& outMetadata,
                           std::string& outError) {
    outMetadata = CacheEntryMetadata{};
    std::ifstream file(metadataPath);
    if (!file) {
        outError = "Could not open cache metadata '" + metadataPath.string() + "'.";
        return false;
    }

    std::string line;
    size_t lineNumber = 0;
    while (std::getline(file, line)) {
        ++lineNumber;
        const std::string content = stripComment(line);
        if (content.empty()) {
            continue;
        }

        const size_t equals = content.find('=');
        if (equals == std::string::npos) {
            outError = "Invalid cache metadata line " + std::to_string(lineNumber) +
                       ": expected key = value.";
            return false;
        }

        const std::string key = trim(std::string_view(content).substr(0, equals));
        const std::string value =
            trim(std::string_view(content).substr(equals + 1));

        if (key == "dependency_groups") {
            if (!parseQuotedStringArray(value, outMetadata.dependencyGroups,
                                        outError)) {
                outError = "Invalid cache metadata line " +
                           std::to_string(lineNumber) + ": " + outError;
                return false;
            }
            continue;
        }

        std::string parsed;
        if (!parseQuotedString(value, parsed, outError)) {
            outError = "Invalid cache metadata line " +
                       std::to_string(lineNumber) + ": " + outError;
            return false;
        }

        if (key == "package_id") {
            outMetadata.packageId = parsed;
        } else if (key == "version") {
            outMetadata.version = parsed;
        } else if (key == "kind") {
            outMetadata.kind = parsed;
        } else if (key == "source_type") {
            outMetadata.sourceType = parsed;
        } else if (key == "source_path") {
            outMetadata.sourcePath = parsed;
        } else if (key == "manifest_digest") {
            outMetadata.manifestDigest = parsed;
        } else if (key == "api_digest") {
            outMetadata.apiDigest = parsed;
        } else {
            outError = "Unsupported cache metadata field '" + key + "'.";
            return false;
        }
    }

    outMetadata.dependencyGroups =
        sortedUniqueStrings(std::move(outMetadata.dependencyGroups));
    return true;
}

bool cacheMetadataMatchesEntry(const CacheEntryMetadata& metadata,
                               const PackageRegistryEntry& entry) {
    return metadata.packageId == entry.packageId &&
           metadata.version == entry.version && metadata.kind == entry.kind &&
           metadata.sourceType == entry.sourceType &&
           metadata.sourcePath == entry.sourcePath &&
           metadata.manifestDigest == entry.manifestDigest &&
           metadata.apiDigest == entry.apiDigest &&
           metadata.dependencyGroups ==
               sortedUniqueStrings(entry.dependencyGroups);
}

bool addAvailableNode(std::unordered_map<std::string, PackageNode>& outNodes,
                      PackageNode node, std::string& outError) {
    auto existing = outNodes.find(node.entry.packageId);
    if (existing != outNodes.end()) {
        if (existing->second.packageDir != node.packageDir) {
            outError = "Duplicate local package '" + node.entry.packageId +
                       "' found at '" + existing->second.packageDir.string() +
                       "' and '" + node.packageDir.string() + "'.";
            return false;
        }
        return true;
    }

    outNodes[node.entry.packageId] = std::move(node);
    return true;
}

bool scanPackageDirectories(const std::filesystem::path& root,
                            std::unordered_map<std::string, PackageNode>& outNodes,
                            std::string& outError) {
    std::error_code ec;
    if (!std::filesystem::exists(root, ec) || ec) {
        return true;
    }

    for (std::filesystem::recursive_directory_iterator it(root, ec), end;
         !ec && it != end; it.increment(ec)) {
        if (ec || !it->is_directory()) {
            continue;
        }

        const std::filesystem::path dir = it->path();
        if (!fileExists(dir / kProjectManifestFileName) &&
            !fileExists(dir / "package.toml")) {
            continue;
        }

        PackageNode node;
        if (!loadPackageEntryFromDir(dir, node.entry, nullptr, outError)) {
            continue;
        }
        node.packageDir = std::filesystem::path(node.entry.packageDir);
        if (!addAvailableNode(outNodes, std::move(node), outError)) {
            return false;
        }
    }

    return true;
}

bool scanWorkspaceMemberPackages(
    const std::filesystem::path& projectRoot, const ProjectManifestData& manifest,
    std::unordered_map<std::string, PackageNode>& outNodes,
    std::unordered_set<std::string>& outWorkspacePackageIds, std::string& outError) {
    for (const std::string& member : manifest.workspaceMembers) {
        const std::filesystem::path memberPath = projectRoot / member;
        if (!isDirectory(memberPath)) {
            outError = "Workspace member '" + member + "' does not exist.";
            return false;
        }

        PackageNode node;
        if (!loadPackageEntryFromDir(memberPath, node.entry, nullptr, outError)) {
            outError = "Could not load workspace member '" + member + "': " +
                       outError;
            return false;
        }

        node.packageDir = std::filesystem::path(node.entry.packageDir);
        node.entry.sourceType = "workspace";
        node.entry.sourcePath = canonicalOrLexical(memberPath);
        if (!addAvailableNode(outNodes, node, outError)) {
            return false;
        }
        outWorkspacePackageIds.insert(node.entry.packageId);
    }

    return true;
}

void ensureResolvedLibraryPath(PackageNode& node, const std::string& projectRoot) {
    if (node.entry.kind != "native" || !node.entry.libraryPath.empty()) {
        return;
    }

    const std::string workspaceRoot =
        inferWorkspaceRoot(node.packageDir, node.entry, projectRoot);
    node.entry.libraryPath = canonicalOrLexical(
        std::filesystem::path(workspaceRoot) / "build" / "packages" /
        node.entry.packageNamespace / node.entry.packageName /
        kPackageLibraryFileName);
}

bool resolveDependencyNode(
    const std::string& projectRoot, const ProjectDependencySpec& dependency,
    const std::unordered_map<std::string, PackageNode>& available,
    const std::unordered_set<std::string>& workspacePackageIds, PackageNode& outNode,
    std::string& outError) {
    outNode = PackageNode{};

    if (dependency.workspace) {
        if (dependency.packageId.empty()) {
            outError = "Workspace dependency '" + dependency.alias +
                       "' must declare package = \"namespace:name\".";
            return false;
        }

        auto it = available.find(dependency.packageId);
        if (it == available.end() ||
            workspacePackageIds.find(dependency.packageId) ==
                workspacePackageIds.end()) {
            outError = "Workspace dependency '" + dependency.alias +
                       "' could not find workspace member '" +
                       dependency.packageId + "'.";
            return false;
        }
        outNode = it->second;
        outNode.entry.sourceType = "workspace";
        outNode.entry.sourcePath = outNode.packageDir.string();
    } else if (!dependency.path.empty()) {
        const std::filesystem::path dependencyPath =
            std::filesystem::path(projectRoot) / dependency.path;
        if (!loadPackageEntryFromDir(dependencyPath, outNode.entry, nullptr,
                                     outError)) {
            outError = "Could not load dependency '" + dependency.alias + "': " +
                       outError;
            return false;
        }

        outNode.packageDir = std::filesystem::path(outNode.entry.packageDir);
        outNode.entry.sourceType = "path";
        outNode.entry.sourcePath = canonicalOrLexical(dependencyPath);
    } else if (!dependency.git.empty()) {
        outError = "Dependency '" + dependency.alias +
                   "' uses git sources, which are recognized but not implemented until Phase 2.";
        return false;
    } else if (!dependency.registry.empty()) {
        outError = "Dependency '" + dependency.alias +
                   "' uses named registries, which are recognized but not implemented until Phase 2.";
        return false;
    } else if (!dependency.packageId.empty()) {
        outError = "Dependency '" + dependency.alias +
                   "' requires published package resolution, which is not implemented until Phase 2.";
        return false;
    } else {
        outError = "Dependency '" + dependency.alias + "' does not declare a usable source.";
        return false;
    }

    ensureResolvedLibraryPath(outNode, projectRoot);

    if (!dependency.packageId.empty() &&
        dependency.packageId != outNode.entry.packageId) {
        outError = "Dependency '" + dependency.alias + "' declares package '" +
                   dependency.packageId + "' but resolves to '" +
                   outNode.entry.packageId + "'.";
        return false;
    }

    if (!dependency.version.empty() && dependency.version != outNode.entry.version) {
        outError = "Dependency '" + dependency.alias + "' requires version '" +
                   dependency.version + "' but local package '" +
                   outNode.entry.packageId + "' reports '" +
                   outNode.entry.version + "'.";
        return false;
    }

    return true;
}

bool validatePackageEntry(const PackageRegistryEntry& entry,
                          const std::string& projectRoot,
                          std::string& outError) {
    const std::filesystem::path packageDir(entry.packageDir);
    if (entry.kind == "native") {
        const std::string validationRoot =
            inferWorkspaceRoot(packageDir, entry, projectRoot);
        return validatePackageDirectory(packageDir.string(), validationRoot,
                                        outError);
    }

    if (entry.entryPath.empty() || !fileExists(entry.entryPath)) {
        outError = "Source package '" + entry.importName +
                   "' is missing entry module '" + entry.entryPath + "'.";
        return false;
    }

    if (!entry.apiPath.empty()) {
        PackageApiMetadata apiMetadata;
        if (!loadPackageApiMetadata(entry.apiPath, entry.packageId, entry.importName,
                                    apiMetadata, outError)) {
            return false;
        }
    }

    return true;
}

bool materializeCacheEntry(const PackageRegistryEntry& sourceEntry,
                           const std::filesystem::path& cacheDir,
                           std::string& outError) {
    if (!removePathIfExists(cacheDir, outError)) {
        return false;
    }

    std::error_code ec;
    std::filesystem::create_directories(cacheDir, ec);
    if (ec) {
        outError = "Could not create cache directory '" + cacheDir.string() + "'.";
        return false;
    }

    const std::filesystem::path sourceDir(sourceEntry.sourcePath);
    if (sourceEntry.kind == "source") {
        if (!copyDirectoryRecursive(sourceDir, cacheDir, outError)) {
            return false;
        }
        return writeCacheMetadataFile(cacheMetadataPath(cacheDir), sourceEntry,
                                      outError);
    }

    const std::filesystem::path sourceManifest = fileExists(sourceDir / kProjectManifestFileName)
                                                     ? sourceDir / kProjectManifestFileName
                                                     : sourceDir / "package.toml";
    if (!copyFileReplacing(sourceManifest, cacheDir / kProjectManifestFileName,
                           outError)) {
        return false;
    }

    if (!sourceEntry.apiPath.empty() &&
        !copyFileReplacing(sourceEntry.apiPath, cacheDir / kPackageApiFileName,
                           outError)) {
        return false;
    }

    if (sourceEntry.libraryPath.empty()) {
        outError = "Native package '" + sourceEntry.importName +
                   "' does not have a built library to install.";
        return false;
    }

    if (!copyFileReplacing(sourceEntry.libraryPath,
                           cacheDir / kPackageLibraryFileName, outError)) {
        return false;
    }

    return writeCacheMetadataFile(cacheMetadataPath(cacheDir), sourceEntry, outError);
}

bool materializeProjectInstall(const PackageRegistryEntry& sourceEntry,
                               const std::filesystem::path& projectRoot,
                               PackageRegistryEntry& outInstalled,
                               std::string& outError) {
    outInstalled = sourceEntry;

    const std::string digestSeed = sourceEntry.version + "|" +
                                   sourceEntry.manifestDigest + "|" +
                                   sourceEntry.apiDigest + "|" +
                                   sourceEntry.sourcePath;
    const std::string installKey = hashString(digestSeed);
    const std::filesystem::path cacheRoot =
        preferredLocalCacheRoot(projectRoot);
    const std::filesystem::path cacheDir =
        cacheRoot / sourceEntry.packageNamespace / sourceEntry.packageName /
        installKey;
    const std::filesystem::path installDir =
        installPackagesRoot(projectRoot) / sourceEntry.packageNamespace /
        sourceEntry.packageName;

    CacheEntryMetadata metadata;
    std::string metadataError;
    const bool hasReusableCache =
        isDirectory(cacheDir) && fileExists(cacheMetadataPath(cacheDir)) &&
        loadCacheMetadataFile(cacheMetadataPath(cacheDir), metadata, metadataError) &&
        cacheMetadataMatchesEntry(metadata, sourceEntry);

    if (!hasReusableCache) {
        if (!materializeCacheEntry(sourceEntry, cacheDir, outError)) {
            return false;
        }
    }

    if (!removePathIfExists(installDir, outError)) {
        return false;
    }
    if (!ensureParentDirectory(installDir, outError)) {
        return false;
    }

    if (!copyDirectoryRecursive(cacheDir, installDir, outError)) {
        return false;
    }

    outInstalled.packageDir = installDir.lexically_normal().string();
    outInstalled.sourcePath = canonicalOrLexical(sourceEntry.sourcePath);

    const std::filesystem::path installedApi = installDir / kPackageApiFileName;
    if (fileExists(installedApi)) {
        outInstalled.apiPath = installedApi.lexically_normal().string();
    } else {
        outInstalled.apiPath.clear();
    }

    if (sourceEntry.kind == "source") {
        std::filesystem::path relativeEntry =
            std::filesystem::relative(std::filesystem::path(sourceEntry.entryPath),
                                      std::filesystem::path(sourceEntry.sourcePath));
        outInstalled.entryPath = (installDir / relativeEntry).lexically_normal().string();
        outInstalled.libraryPath.clear();
    } else {
        outInstalled.libraryPath =
            (installDir / kPackageLibraryFileName).lexically_normal().string();
        outInstalled.entryPath.clear();
    }

    return validatePackageEntry(outInstalled, projectRoot.string(), outError);
}

bool collectResolvedPackages(
    const std::string& projectRoot, const ProjectManifestData& manifest,
    const InstallOptions& options, std::vector<PackageRegistryEntry>& outEntries,
    std::string& outError) {
    outEntries.clear();
    outError.clear();

    std::unordered_map<std::string, PackageNode> available;
    if (!scanPackageDirectories(std::filesystem::path(projectRoot) / "packages",
                                available, outError)) {
        return false;
    }

    std::unordered_set<std::string> workspacePackageIds;
    if (!scanWorkspaceMemberPackages(std::filesystem::path(projectRoot), manifest,
                                     available, workspacePackageIds,
                                     outError)) {
        return false;
    }

    std::vector<DependencyRoot> roots;
    auto appendDependencies =
        [&](const std::vector<ProjectDependencySpec>& dependencies,
            const char* groupName) -> bool {
        for (const auto& dependency : dependencies) {
            if (options.offline &&
                dependency.path.empty() && !dependency.workspace) {
                outError = "Dependency '" + dependency.alias +
                           "' cannot be installed with --offline because it is not a local path or workspace dependency.";
                return false;
            }

            PackageNode node;
            if (!resolveDependencyNode(projectRoot, dependency, available,
                                       workspacePackageIds, node, outError)) {
                return false;
            }

            if (!addAvailableNode(available, node, outError)) {
                return false;
            }

            roots.push_back(DependencyRoot{std::move(node), groupName});
        }
        return true;
    };

    if (!appendDependencies(manifest.dependencies, "runtime")) {
        return false;
    }
    if (options.includeDevDependencies &&
        !appendDependencies(manifest.devDependencies, "dev")) {
        return false;
    }

    std::sort(roots.begin(), roots.end(),
              [](const DependencyRoot& lhs, const DependencyRoot& rhs) {
                  if (lhs.node.entry.packageId != rhs.node.entry.packageId) {
                      return lhs.node.entry.packageId < rhs.node.entry.packageId;
                  }
                  return lhs.group < rhs.group;
              });

    std::unordered_map<std::string, std::unordered_set<std::string>> groupsById;
    std::unordered_set<std::string> finished;
    std::unordered_set<std::string> inProgressPairs;
    std::vector<PackageRegistryEntry> ordered;

    std::function<bool(const PackageNode&, const std::string&)> visit =
        [&](const PackageNode& node, const std::string& group) {
            if (!groupsById[node.entry.packageId].insert(group).second) {
                return true;
            }

            const std::string pairKey = node.entry.packageId + "|" + group;
            if (!inProgressPairs.insert(pairKey).second) {
                outError = "Package dependency cycle detected at '" +
                           node.entry.packageId + "'.";
                return false;
            }

            for (const std::string& dependencyId : node.entry.dependencyIds) {
                auto dependencyIt = available.find(dependencyId);
                if (dependencyIt == available.end()) {
                    outError = "Package '" + node.entry.packageId +
                               "' depends on '" + dependencyId +
                               "', but no local package provides it.";
                    return false;
                }
                if (!visit(dependencyIt->second, group)) {
                    return false;
                }
            }

            inProgressPairs.erase(pairKey);
            if (finished.insert(node.entry.packageId).second) {
                ordered.push_back(node.entry);
            }
            return true;
        };

    for (const auto& root : roots) {
        if (!visit(root.node, root.group)) {
            return false;
        }
    }

    for (auto& entry : ordered) {
        auto groupsIt = groupsById.find(entry.packageId);
        if (groupsIt != groupsById.end()) {
            entry.dependencyGroups = sortedUniqueStrings(
                std::vector<std::string>(groupsIt->second.begin(),
                                         groupsIt->second.end()));
        }
    }

    std::sort(ordered.begin(), ordered.end(),
              [](const PackageRegistryEntry& lhs, const PackageRegistryEntry& rhs) {
                  if (lhs.importName != rhs.importName) {
                      return lhs.importName < rhs.importName;
                  }
                  return lhs.packageId < rhs.packageId;
              });

    for (const auto& entry : ordered) {
        if (!validatePackageEntry(entry, projectRoot, outError)) {
            return false;
        }
    }

    outEntries = std::move(ordered);
    return true;
}

bool packageEntryMatchesLocked(const PackageRegistryEntry& expected,
                               const PackageRegistryEntry& actual) {
    return expected.packageId == actual.packageId &&
           expected.importName == actual.importName &&
           expected.packageNamespace == actual.packageNamespace &&
           expected.packageName == actual.packageName &&
           expected.version == actual.version &&
           expected.kind == actual.kind &&
           expected.sourceType == actual.sourceType &&
           expected.sourcePath == actual.sourcePath &&
           expected.manifestDigest == actual.manifestDigest &&
           expected.apiDigest == actual.apiDigest &&
           sortedUniqueStrings(expected.dependencyIds) ==
               sortedUniqueStrings(actual.dependencyIds) &&
           sortedUniqueStrings(expected.dependencyGroups) ==
               sortedUniqueStrings(actual.dependencyGroups);
}

bool validateLockedGraph(const std::vector<PackageRegistryEntry>& resolvedEntries,
                         const std::vector<PackageRegistryEntry>& lockedEntries,
                         std::string& outError) {
    if (resolvedEntries.size() != lockedEntries.size()) {
        outError = "mog.lock is out of date with mog.toml: resolved " +
                   std::to_string(resolvedEntries.size()) + " package(s), but lockfile has " +
                   std::to_string(lockedEntries.size()) + ".";
        return false;
    }

    std::unordered_map<std::string, PackageRegistryEntry> lockedById;
    for (const auto& entry : lockedEntries) {
        lockedById[entry.packageId] = entry;
    }

    for (const auto& resolved : resolvedEntries) {
        auto lockedIt = lockedById.find(resolved.packageId);
        if (lockedIt == lockedById.end()) {
            outError = "mog.lock is missing package '" + resolved.packageId + "'.";
            return false;
        }

        if (!packageEntryMatchesLocked(resolved, lockedIt->second)) {
            outError = "mog.lock is out of date for package '" +
                       resolved.packageId + "'. Run 'mog install' to refresh it.";
            return false;
        }
    }

    return true;
}

bool materializeInstalledPackages(const std::string& projectRoot,
                                  const std::vector<PackageRegistryEntry>& resolved,
                                  std::vector<PackageRegistryEntry>& outEntries,
                                  std::string& outError) {
    outEntries.clear();
    outEntries.reserve(resolved.size());
    for (const auto& entry : resolved) {
        PackageRegistryEntry installedEntry;
        if (!materializeProjectInstall(entry, std::filesystem::path(projectRoot),
                                       installedEntry, outError)) {
            return false;
        }
        outEntries.push_back(std::move(installedEntry));
    }
    return true;
}

void sortDependencies(std::vector<ProjectDependencySpec>& dependencies) {
    std::sort(dependencies.begin(), dependencies.end(),
              [](const ProjectDependencySpec& lhs,
                 const ProjectDependencySpec& rhs) {
                  return lhs.alias < rhs.alias;
              });
}

void writeDependencyTable(std::ofstream& out, const char* tableName,
                          const std::vector<ProjectDependencySpec>& dependencies) {
    if (dependencies.empty()) {
        return;
    }

    out << "\n[" << tableName << "]\n";
    for (const auto& dependency : dependencies) {
        out << dependency.alias << " = { ";
        bool needsComma = false;
        if (!dependency.path.empty()) {
            out << "path = " << quoteTomlString(normalizeRelativePath(dependency.path));
            needsComma = true;
        }
        if (dependency.workspace) {
            if (needsComma) {
                out << ", ";
            }
            out << "workspace = true";
            needsComma = true;
        }
        if (!dependency.packageId.empty()) {
            if (needsComma) {
                out << ", ";
            }
            out << "package = " << quoteTomlString(dependency.packageId);
            needsComma = true;
        }
        if (!dependency.version.empty()) {
            if (needsComma) {
                out << ", ";
            }
            out << "version = " << quoteTomlString(dependency.version);
            needsComma = true;
        }
        if (!dependency.git.empty()) {
            if (needsComma) {
                out << ", ";
            }
            out << "git = " << quoteTomlString(dependency.git);
            needsComma = true;
        }
        if (!dependency.registry.empty()) {
            if (needsComma) {
                out << ", ";
            }
            out << "registry = " << quoteTomlString(dependency.registry);
        }
        out << " }\n";
    }
}

}  // namespace

bool loadProjectManifestData(const std::string& projectRoot,
                             ProjectManifestData& outManifest,
                             std::string& outError) {
    outManifest = ProjectManifestData{};
    outManifest.name = defaultProjectName(projectRoot);
    outManifest.description = outManifest.name + " project";
    outError.clear();

    const std::filesystem::path manifestPath =
        std::filesystem::path(projectRoot) / kProjectManifestFileName;
    std::ifstream file(manifestPath);
    if (!file) {
        outError = "Could not open project manifest '" + manifestPath.string() + "'.";
        return false;
    }

    enum class Section {
        ROOT,
        WORKSPACE,
        DEPENDENCIES,
        DEV_DEPENDENCIES,
    };

    Section section = Section::ROOT;
    std::string line;
    size_t lineNumber = 0;
    while (std::getline(file, line)) {
        ++lineNumber;
        const std::string content = stripComment(line);
        if (content.empty()) {
            continue;
        }

        if (content == "[dependencies]") {
            section = Section::DEPENDENCIES;
            continue;
        }
        if (content == "[dev-dependencies]") {
            section = Section::DEV_DEPENDENCIES;
            continue;
        }
        if (content == "[workspace]") {
            section = Section::WORKSPACE;
            continue;
        }

        if (content.front() == '[' && content.back() == ']') {
            outError = "Unsupported project manifest section '" + content + "'.";
            return false;
        }

        const size_t equals = content.find('=');
        if (equals == std::string::npos) {
            outError = "Invalid project manifest line " + std::to_string(lineNumber) +
                       ": expected key = value.";
            return false;
        }

        const std::string key = trim(std::string_view(content).substr(0, equals));
        const std::string value =
            trim(std::string_view(content).substr(equals + 1));
        std::string parseError;

        if (section == Section::ROOT) {
            if (key == "kind") {
                if (!parseQuotedString(value, outManifest.kind, parseError)) {
                    outError = parseError;
                    return false;
                }
            } else if (key == "name") {
                if (!parseQuotedString(value, outManifest.name, parseError)) {
                    outError = parseError;
                    return false;
                }
            } else if (key == "version") {
                if (!parseQuotedString(value, outManifest.version, parseError)) {
                    outError = parseError;
                    return false;
                }
            } else if (key == "description") {
                if (!parseQuotedString(value, outManifest.description, parseError)) {
                    outError = parseError;
                    return false;
                }
            } else {
                continue;
            }
            continue;
        }

        if (section == Section::WORKSPACE) {
            if (key != "members") {
                outError = "Unsupported workspace field '" + key + "'.";
                return false;
            }
            if (!parseQuotedStringArray(value, outManifest.workspaceMembers,
                                        parseError)) {
                outError = "Invalid workspace field '" + key + "': " + parseError;
                return false;
            }
            for (auto& member : outManifest.workspaceMembers) {
                member = normalizeRelativePath(member);
            }
            outManifest.workspaceMembers =
                sortedUniqueStrings(std::move(outManifest.workspaceMembers));
            continue;
        }

        ProjectDependencySpec dependency;
        dependency.alias = key;
        if (!parseDependencyInlineTable(value, dependency, parseError)) {
            outError = "Invalid dependency '" + key + "': " + parseError;
            return false;
        }
        if (section == Section::DEPENDENCIES) {
            outManifest.dependencies.push_back(std::move(dependency));
        } else {
            outManifest.devDependencies.push_back(std::move(dependency));
        }
    }

    if (outManifest.kind.empty()) {
        outManifest.kind = "project";
    }
    if (outManifest.kind != "project") {
        outError = "Root mog.toml must declare kind = \"project\".";
        return false;
    }

    sortDependencies(outManifest.dependencies);
    sortDependencies(outManifest.devDependencies);
    return true;
}

bool writeProjectManifestData(const std::string& projectRoot,
                              const ProjectManifestData& manifest,
                              std::string& outError) {
    outError.clear();

    const std::filesystem::path manifestPath =
        std::filesystem::path(projectRoot) / kProjectManifestFileName;
    std::ofstream out(manifestPath);
    if (!out) {
        outError = "Could not open '" + manifestPath.string() + "' for writing.";
        return false;
    }

    out << "kind = " << quoteTomlString("project") << "\n";
    out << "name = " << quoteTomlString(manifest.name) << "\n";
    out << "version = " << quoteTomlString(manifest.version) << "\n";
    out << "description = " << quoteTomlString(manifest.description) << "\n";
    if (!manifest.workspaceMembers.empty()) {
        out << "\n[workspace]\n";
        out << "members = "
            << quoteTomlArray(sortedUniqueStrings(manifest.workspaceMembers))
            << "\n";
    }

    std::vector<ProjectDependencySpec> dependencies = manifest.dependencies;
    std::vector<ProjectDependencySpec> devDependencies = manifest.devDependencies;
    sortDependencies(dependencies);
    sortDependencies(devDependencies);

    writeDependencyTable(out, "dependencies", dependencies);
    writeDependencyTable(out, "dev-dependencies", devDependencies);
    return true;
}

bool initializeProjectManifest(const std::string& projectRoot,
                               const std::string& projectName,
                               std::string& outError) {
    ProjectManifestData manifest;
    manifest.name = projectName.empty() ? defaultProjectName(projectRoot) : projectName;
    manifest.description = manifest.name + " project";
    return writeProjectManifestData(projectRoot, manifest, outError);
}

bool discoverLocalDependencySpec(const std::string& projectRoot,
                                 const std::string& rawSpecifier,
                                 ProjectDependencySpec& outDependency,
                                 std::string& outError) {
    outDependency = ProjectDependencySpec{};
    outError.clear();

    const std::string packageId = normalizePackageIdLikeSpecifier(rawSpecifier);
    ProjectManifestData manifest;
    if (!loadProjectManifestData(projectRoot, manifest, outError)) {
        return false;
    }

    std::unordered_map<std::string, PackageNode> available;
    if (!scanPackageDirectories(std::filesystem::path(projectRoot) / "packages",
                                available, outError)) {
        return false;
    }
    std::unordered_set<std::string> workspacePackageIds;
    if (!scanWorkspaceMemberPackages(std::filesystem::path(projectRoot), manifest,
                                     available, workspacePackageIds,
                                     outError)) {
        return false;
    }

    const PackageNode* matched = nullptr;
    for (const auto& [candidateId, node] : available) {
        if (node.entry.importName == rawSpecifier || candidateId == rawSpecifier ||
            (!packageId.empty() && candidateId == packageId)) {
            matched = &node;
            break;
        }
    }

    if (matched == nullptr) {
        outError = "Cannot discover a local package matching '" + rawSpecifier + "'.";
        return false;
    }

    outDependency.alias = matched->entry.importName;
    outDependency.packageId = matched->entry.packageId;
    outDependency.version = matched->entry.version;
    if (workspacePackageIds.find(matched->entry.packageId) !=
        workspacePackageIds.end()) {
        outDependency.workspace = true;
    } else {
        relativePathString(projectRoot, matched->packageDir, outDependency.path);
    }
    return true;
}

bool addProjectDependency(const std::string& projectRoot,
                          const ProjectDependencySpec& dependency,
                          std::string& outError) {
    ProjectManifestData manifest;
    if (!loadProjectManifestData(projectRoot, manifest, outError)) {
        return false;
    }

    auto existing = std::find_if(
        manifest.dependencies.begin(), manifest.dependencies.end(),
        [&](const ProjectDependencySpec& candidate) {
            return candidate.alias == dependency.alias;
        });
    if (existing != manifest.dependencies.end()) {
        *existing = dependency;
    } else {
        manifest.dependencies.push_back(dependency);
    }

    sortDependencies(manifest.dependencies);
    return writeProjectManifestData(projectRoot, manifest, outError);
}

bool installProjectPackages(const std::string& projectRoot,
                            std::vector<PackageRegistryEntry>& outEntries,
                            const InstallOptions& options,
                            std::string& outError) {
    ProjectManifestData manifest;
    if (!loadProjectManifestData(projectRoot, manifest, outError)) {
        return false;
    }

    std::vector<PackageRegistryEntry> resolvedEntries;
    if (!collectResolvedPackages(projectRoot, manifest, options, resolvedEntries,
                                 outError)) {
        return false;
    }

    if (options.locked) {
        std::vector<PackageRegistryEntry> lockedEntries;
        if (!loadProjectLockfile(projectRoot, lockedEntries, outError)) {
            return false;
        }
        if (!validateLockedGraph(resolvedEntries, lockedEntries, outError)) {
            return false;
        }
    }

    if (!materializeInstalledPackages(projectRoot, resolvedEntries, outEntries,
                                      outError)) {
        return false;
    }

    const std::filesystem::path projectRootPath(projectRoot);
    const std::filesystem::path registryPath = installRegistryPath(projectRootPath);
    if (!writeInstallRegistryFile(registryPath, projectRootPath, outEntries,
                                  outError)) {
        return false;
    }

    if (!options.locked) {
        const std::filesystem::path lockfilePath = projectRootPath / kLockfileName;
        if (!writeLockfile(lockfilePath, projectRootPath, resolvedEntries, outError)) {
            return false;
        }
    }

    std::error_code ec;
    std::filesystem::create_directories(preferredLocalCacheRoot(projectRootPath),
                                        ec);
    return true;
}

bool ensureProjectPackagesInstalled(const std::string& projectRoot,
                                    const InstallOptions& options,
                                    std::string& outError) {
    outError.clear();

    ProjectManifestData manifest;
    if (!loadProjectManifestData(projectRoot, manifest, outError)) {
        return false;
    }

    if (manifest.dependencies.empty() &&
        (!options.includeDevDependencies || manifest.devDependencies.empty())) {
        return true;
    }

    const std::filesystem::path registryPath =
        installRegistryPath(std::filesystem::path(projectRoot));
    const std::filesystem::path manifestPath =
        std::filesystem::path(projectRoot) / kProjectManifestFileName;

    std::error_code ec;
    if (!options.locked && std::filesystem::exists(registryPath, ec) && !ec) {
        const auto registryTime = std::filesystem::last_write_time(registryPath, ec);
        if (!ec) {
            const auto manifestTime =
                std::filesystem::last_write_time(manifestPath, ec);
            if (!ec && registryTime >= manifestTime) {
                return true;
            }
        }
    }

    std::vector<PackageRegistryEntry> installedEntries;
    return installProjectPackages(projectRoot, installedEntries, options, outError);
}
